apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: candy-deployment
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: candy-ws
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: candy-ws
    spec:
      containers:
      - image: linuxacademycontent/candy-service:2
        imagePullPolicy: IfNotPresent
        name: candy-ws
